/* JustinGuitar lesson data. Only Grade 1 is verified (copied from Fretlog); Grades 2 and 3 are not loaded yet.
   Each module: [title, [[lessonTitle, slug, youtubeId], ...]]. An empty youtubeId means no video. */
(function (root) {
  "use strict";
  const GRADE1 = [
 ["Before You Begin: Guitar Basics",[["How To Tune A Guitar For Beginners","how-to-tune-a-guitar-for-beginners-b1-101","X2EmpWr9vUc"],["How To Hold Your Guitar","how-to-hold-your-guitar-b1-102","MlV6WhM9YhE"],["Positive Finger Placement","positive-finger-placement-b1-103","VB0vWNqNMbA"],["How To Read Guitar Chord Boxes","how-to-read-guitar-chord-boxes-b1-104","LlN2yrFQKzY"],["How To Hold A Guitar Pick","how-to-hold-a-guitar-pick-b1-106","-04Et5qIoa4"],["How To Strum Without A Pick","how-to-strum-without-a-pick-b1-107","j-ljksb6oIY"]]],
 ["Module 1 · A & D Chords: Play Your First Song",[["How To Play The D Chord","how-to-play-the-d-chord-b1-105","QkrIZBLZEXw"],["How To Play The A Chord","how-to-play-the-a-chord-b1-108","1X2rW5ATdLQ"],["How To Use Anchor Fingers","how-to-use-anchor-fingers-b1-109","Se__aa_k-ms"],["One Minute Changes Exercise","one-minute-changes-exercise-b1-110","mAgc7hr44WM"],["Bars & Strumming On 1","bars-strumming-on-1-b1-111","n45PDizCRLw"],["How To Strum The Correct Strings","how-to-strum-the-correct-strings-b1-112","72MEHvT9JV4"],["How To Minimize Finger Pain","how-to-minimize-finger-pain-b1-113","V0Q0buwLvVA"],["Super Easy 2 Chord Songs","super-easy-2-chord-songs-b1-114","E5do76H_mi0"],["How To Use Justin's Song App","how-to-use-justin-s-song-app-b1-115","kLYT2B8gyzQ"],["Module 1 Practice Routine","module-1-practice-routine-b1-116","uBZsLmmOz9I"],["Using My Practice Assistant","using-my-practice-assistant-b1-117","IE5HWnrP9Wk"],["When to move on from Module 1?","when-to-move-on-from-module-1-b1-118","-SAo7bvQzmA"]]],
 ["Module 2 · Rhythm & Chord Changes + Your First Riff",[["How To Play The E Chord","how-to-play-the-e-chord-b1-201","9NSoRXC9PJI"],["E Chord Anchors & Tricks","e-chord-anchors-tricks-b1-202","McSfLPmXcLw"],["Tapping Your Foot","tapping-your-foot-b1-203","RPBtKqD6ddQ"],["Strumming Mechanics","strumming-mechanics-b1-204","c5pipuvb-EM"],["Strumming On The Beat","strumming-on-the-beat-b1-205","JRhwvxl46-8"],["Chord Changes For One","chord-changes-for-one-b1-206","7VzPzBsm4sU"],["Peter Gunn Theme","peter-gunn-theme-b1-207","FZ9mkji_8PU"],["Songs For Module 2","songs-for-module-2-b1-208","p5Ln39q8cj4"],["Module 2 Practice Routine","module-2-practice-routine-b1-209","gI8iH5Mg7LQ"]]],
 ["Module 3 · Capo, Minor Chords & Up Strums",[["What Are Minor Chords","what-are-minor-chords-b1-301","pbIqk8tTdbw"],["The E Minor Chord","the-e-minor-chord-b1-302","lqcd3jVysXY"],["The A Minor Chord","the-a-minor-chord-b1-303","1Y2veGF9s44"],["Holding the Guitar","holding-the-guitar-b1-304","C-mt8td1teU"],["Counting Ands","counting-ands-b1-305","U1TMGzcbbLE"],["All About Up Strums","all-about-up-strums-b1-306","JrIxNphnhrM"],["Strumming Patterns With Ups","strumming-patterns-with-ups-b1-307","IXL1bG_ao3c"],["All About Capos","all-about-capos-b1-308","A4mEBSFn-7w"],["Seven Nation Army","seven-nation-army-b1-309","2LEO5xc9rEA"],["Songs For Module 3","songs-for-module-3-b1-310","XxICTF-NIZ8"],["Module 3 Practice Routine","module-3-practice-routine-b1-311","qckkf38Xk2Y"]]],
 ["Module 4 · Metronome, Stretches & The Pattern",[["Beginner Finger Stretches","beginner-finger-stretches-b1-401","qYx8r0EtGsE"],["The D Minor Chord","the-d-minor-chord-b1-402","8mFF8NYVdtI"],["Meet The Metronome","meet-the-metronome-b1-403","sNa44EmrsDc"],["THE Strumming Pattern","the-strumming-pattern-b1-404","6LmQCdt_ZhQ"],["How To Read Guitar TAB","how-to-read-guitar-tab-b1-405","9xsG7n4Jalo"],["Sunshine Of Your Love","sunshine-of-your-love-b1-406","Li4urYsFbHQ"],["Songs For Module 4","songs-for-module-4-b1-407","CWL_O9kR_b0"],["Module 4 Practice Routine","module-4-practice-routine-b1-408","wZ15h9ryY5E"]]],
 ["Module 5 · Basic Theory & Strumming Development",[["The C Chord","the-c-chord-b1-501","f18EV2dr008"],["Guitar Strumming Tips","guitar-strumming-tips-b1-502","CjM5fyXoV8w"],["Exploring Strumming","exploring-strumming-b1-503","0EbliWAtnw0"],["Understanding Music Notes","understanding-music-notes-b1-504","Ah-brqdByAY"],["Your Own Songbook","your-own-songbook-b1-505","0GTuvZmVDUY"],["RIFF Come As You Are","riff-come-as-you-are-b1-506","0EVHt__Ktnw"],["Songs For Module 5","songs-for-module-5-b1-507","k3PM4Qc0N-s"],["Module 5 Practice","module-5-practice-b1-508","7rQGeJwWfe0"]]],
 ["Module 6 · 6:8 Time, Fast Changes & Alternate Picking",[["Beginner Alternate Picking","beginner-alternate-picking-b1-601","q8SHmo1-dac"],["The G Chord... hacked!","the-g-chord-hacked-b1-602","i0G69vCTv4s"],["About Time Signatures","about-time-signatures-b1-603","FDPWwviOYno"],["A 6:8 Strumming Pattern","a-6-8-strumming-pattern-b1-604","bKOmcPTHYpA"],["Open String Note Names","open-string-note-names-b1-605","CF08-EwA-nY"],["Forcing Chord Changes","forcing-chord-changes-b1-606","d9YRzCF5A9M"],["Songs For Module 6","songs-for-module-6-b1-607","MLlWCygtVEc"],["Module 6 Practice","module-6-practice-b1-608","yBxyxZx9oiQ"]]],
 ["Module 7 · Air Changes, Dynamics & Consolidation",[["The 8 Essential Beginner Chord Grips","the-8-essential-beginner-chord-grips-b1-701","lRJ_d3PqPIQ"],["Best Chord Changes To Work On","best-chord-changes-to-work-on-b1-702","SNYMRZqopi8"],["Air Changes (aspire to this!)","air-changes-aspire-to-this-b1-703","9CsY2PRzt94"],["Open Strings Between Changes","open-strings-between-changes-b1-704","p-Rj4svEyrA"],["Feel Good Strumming","feel-good-strumming-b1-705","36cR8twdq7Q"],["Dynamic Improvements","dynamic-improvements-b1-706","mP4knhljqj0"],["Memorize Easy Songs","memorize-easy-songs-b1-707","Rkke83Gvndk"],["Why do Ear Training?","why-do-ear-training-b1-708","bqUdZdhHGVI"],["Why study Music Theory?","why-study-music-theory-b1-709","mB54nIZ-CVs"],["How to PASS Grade 1","how-to-pass-grade-1-b1-710","BI3S9xSK8Iw"],["Module 7 Practice","module-7-practice-b1-711","n-NeP6CTHTc"],["Consolidation Practice Tip","consolidation-practice-tip-b1-712",""],["Grade 1 Feedback Please!","grade-1-feedback-please-b1-7ff",""]]]
];
  const GRADES = {
    1: { modules: GRADE1 },
    2: { modules: null, url: "https://www.justinguitar.com/categories/beginner-guitar-lessons-grade-2" },
    3: { modules: null, url: "https://www.justinguitar.com/" },
  };
  const lessonUrl = slug => "https://www.justinguitar.com/guitar-lessons/" + slug;
  const ALL = [];
  Object.keys(GRADES).forEach(g => (GRADES[g].modules || []).forEach((m, mi) =>
    m[1].forEach(l => ALL.push({ grade: +g, mi, module: m[0], title: l[0], slug: l[1], yt: l[2] }))));
  const BY_SLUG = Object.fromEntries(ALL.map(l => [l.slug, l]));
  const api = { GRADES, ALL, BY_SLUG, lessonUrl };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.FretLessons = api;
})(typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : null);
